version: '3.8'

services:
  # The Redis Broker (Middleman)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # The FastAPI Web Server
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  # The Celery Worker (The code executor)
  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis